Repository entando-ngpl/ng-pipelines-test, pull requests merged in 2021-01, with the labels that each got.

#6 auto merge
  .github/workflows/merge_workflow.yml
  .github/workflows/pull_request_workflow.yml
Labels: approved

#7 debugging logs action
  .github/workflows/merge_workflow.yml
Labels: approved

#8 pr labeled triggering
  .github/workflows/merge_workflow.yml
Labels: approved

#21 Add label
  .github/workflows/owasp-workflow.yml
  .github/workflows/preparation-workflow.yml
  .github/workflows/sonar-workflow.yml
  .github/workflows/tests-workflow.yml
Labels: prepared

#23 retest comment on pull_request retrigger preparation-workflow.yml
  .github/workflows/preparation-workflow.yml
Labels: prepared

#27 single workflow
  .github/workflows/build-and-test-workflow.yml
  .github/workflows/owasp-workflow.yml
  .github/workflows/preparation-workflow.yml
  .github/workflows/sonar-workflow.yml
  .github/workflows/tests-workflow.yml
Labels: DUMMY, no-sonar, prepared

#28 finalization workflow init
  .github/workflows/finalization-workflow.yml
Labels: prepared

#29 Finalization workflow
  .github/workflows/finalization-workflow.yml
  .github/workflows/owasp-workflow.yml
  .github/workflows/sonar-workflow.yml
  .github/workflows/tests-workflow.yml
Labels: prepared

#30 Update README.md
  README.md
Labels: prepared

#31 Update README.md
  README.md
Labels: prepared

#34 Finalization workflow
  .github/workflows/finalization-workflow.yml
Labels: prepared

#35 Merge branch 'main' into finalization-workflow
  .github/workflows/finalization-workflow.yml
Labels: prepared

#36 pom bump test
  .github/workflows/build-and-test-workflow.yml
  .github/workflows/finalization-workflow.yml
Labels: prepared

#37 pom version bump
  .github/workflows/finalization-workflow.yml
Labels: prepared

#39 Single workflow
  .github/workflows/build-and-test-workflow.yml
  README.md
Labels: no-sonar, prepared

#40 removing label after processing
  .github/workflows/build-and-test-workflow.yml
  README.md
Labels: prepared

#42 Finalization workflow
  .github/workflows/build-and-test-workflow.yml
  .github/workflows/finalization-workflow.yml
  README.md
Labels: prepared

#43 push and tag milestone final
  .github/workflows/build-and-test-workflow.yml
  .github/workflows/finalization-workflow.yml
Labels: prepared

#44 credentials fix
  .github/workflows/finalization-workflow.yml
Labels: no-owasp, no-sonar, no-test, prepared

#45 trigger commit
  README.md
Labels: prepared

#46 update commit
  README.md
Labels: prepared

#50 NGP-100 bom check
  .github/workflows/build-and-test-workflow.yml
  .github/workflows/finalization-workflow.yml
  .gitignore
  pom.xml
Labels: prepared

#51 NGP-130 publish on nexus
  .github/workflows/release.yml
  pom.xml
Labels: no-bom-check, prepared

#52 NGP-100 publish on nexus
  .github/workflows/finalization-workflow.yml
  pom.xml
Labels: no-bom-check, prepared

#53 NGP-1001 push tag event
  .github/workflows/release.yml
Labels: no-bom-check, prepared

#54 NGP-123 release event with all types
  .github/workflows/release.yml
Labels: no-bom-check, prepared

#55 NGP-11111 push tag event
  .github/workflows/release.yml
Labels: no-bom-check, prepared

#56 NGP-111 push tag event with branch
  .github/workflows/release.yml
Labels: no-bom-check, prepared

#57 Nexus publishing
  .github/workflows/release.yml
Labels: no-bom-check, no-owasp, no-sonar, no-test
